<aside id="aside" class="omega clearfix">
    <div class="sidebar-widget text_align_center">
        <h5 class="left">Rob Brown</h5>
            <img class="frame" src="<?= $this->baseUrl('images/web/pics/rob.jpg'); ?>" width="220" height="330" alt="Rob Grant">
    </div>

    <hr>

    <div class="sidebar-widget text_align_center">
        <h5 class="left">Grant Leboff</h5>
            <img class="frame" src="<?= $this->baseUrl('/images/web/pics/grant.jpg'); ?>" width="220" height="330" alt="Grant Leboff">
    </div>

    <hr>

    <div class="sidebar-widget text_align_center">
        <h5 class="left">Executive Centre Exterior</h5>
            <img class="frame" src="<?= $this->baseUrl('/images/web/pics/ece.jpg'); ?>" width="220" height="185" alt="Executive Centre Exterior">
    </div>

    <hr>

    <div class="sidebar-widget">
        <h5>BBA <span class="theme_color">Office</span></h5>
        <p>3A Market Square,
        <br>
        Sandy, Bedfordshire SG19 1HT</p>
        <p><b>Tel:</b> 0845-838-0284
        <br>
        <b>Fax:</b> 0845-838-0286
        <br>
        <b>E-mail:</b> <a href="mailto:bookings@newbusinessmasterclass.co.uk">bookings@newbusinessmasterclass.co.uk</a>
    </div>
</aside>