<? $this->placeholder('intro')->captureStart(); ?>
<h2 class="left">
    Booking <span class="theme_color">Complete</span>
</h2>
<h2 class="phone">Call Us: <span class="theme_color">0845</span>-838-0284 </h2>
<? $this->placeholder('intro')->captureEnd(); ?>

<div id="main" class="grid_8 alpha">
    <div class="grid_8">
        <h2>Registration Sent!</h2>
        <p>Thank you for your interest in the New Business Masterclass. We will shortly be
            sending you more information about the event, and a pro-forma invoice for you to
            finalise your booking. Please ensure you can receive mail from
            <span class="theme_color"><b>bookings@newbusinessmasterclass.co.uk</b></span> and that our reply does not get
            identified as junk mail.</p>

            <p>If you have any questions in the meantime, please use the contract details below.</p>
    </div>
</div>

<?= $this->render('index/_sidebar.phtml'); ?>