<? $this->headMeta()->appendName('decription', 'Top Class Business Event Sponsored By BBA Link-Up'); ?>
<? $this->placeholder('slider')->captureStart(); ?>
 <!--start slider-->
<div id="slider_wrap" class="grid_10 push_1 omega">
    <div class="slider_overlay"></div>
        <div id="slider" class="nivoSlider">
            <ul>
                <li><img src="<?= $this->baseUrl('images/web/slider/slider1.jpg'); ?>" alt="slider" title="#htmlcaption1"  width="737" height="420" /></li>
                <li><img src="<?= $this->baseUrl('images/web/slider/slider2.jpg'); ?>" alt="slider" title="#htmlcaption2"  width="737" height="420" /></li>
                <li><img src="<?= $this->baseUrl('images/web/slider/slider3.jpg'); ?>" alt="slider" title="#htmlcaption3" width="737" height="420" /></li>
                <li><img src="<?= $this->baseUrl('images/web/slider/slider4.jpg'); ?>" alt="slider" title="#htmlcaption4" width="737" height="420" /></li>
                <li><img src="<?= $this->baseUrl('images/web/slider/slider5.jpg'); ?>" alt="slider" title="#htmlcaption5" width="737" height="420" /></li>
                <li><img src="<?= $this->baseUrl('images/web/slider/slider6.jpg'); ?>" alt="slider" title="#htmlcaption6" width="737" height="420" /></li>
                <li><img src="<?= $this->baseUrl('images/web/slider/slider7.jpg'); ?>" alt="slider" title="#htmlcaption7" width="737" height="420" /></li>
            </ul>
        </div>
        <!--slider caption 1-->
        <div id="htmlcaption1" class="nivo-html-caption">
            <p>A Top Class Business Event Sponsored By BBA Link-Up</p>
        </div>

        <!--slider caption 1-->
        <div id="htmlcaption2" class="nivo-html-caption">
            <p>Executive Centre Lounge</p>
        </div>

        <!--slider caption 2-->
        <div id="htmlcaption3" class="nivo-html-caption">
            <p>Executive Centre Conference Room</p>
        </div>

        <!--slider caption 3-->
        <div id="htmlcaption4" class="nivo-html-caption">
            <p>Executive Centre Exterior</p>
        </div>

        <!--slider caption 4-->
        <div id="htmlcaption5" class="nivo-html-caption">
            <p>Executive Centre Courtyard</p>
        </div>

        <!--slider caption 5-->
        <div id="htmlcaption6" class="nivo-html-caption">
            <p>Rob Brown</p>
        </div>

        <!--slider caption 6-->
        <div id="htmlcaption7" class="nivo-html-caption">
            <p>Grant Leboff</p>
        </div>
</div>
<!--end slider-->
<? $this->placeholder('slider')->captureEnd(); ?>


<? $this->placeholder('intro')->captureStart(); ?>
<h2 class="text_align_center">
    New Business <span class="theme_color">Masterclass</span>
</h2>

<h4 class="text_align_center">New Business Generation: From Networking to Social Media
    <br>– A masterclass in how to get new customers for your business</h4>
<h5 class="text_align_center">Tuesday, September 4<sup>th</sup> 2012 - Wyboston Lakes Executive Centre, Great North Road, Wyboston,
    Bedfordshire, MK44 3AL</h5>
<? $this->placeholder('intro')->captureEnd(); ?>

<div class="grid_12">
    <p>
        Two international speakers present four major presentations on how ensure that your
        marketing and networking produce the best results.
    </p>

    <div>&nbsp;</div>

    <div class="grid_6 alpha">
        <h4>Rob Brown</h4>
        <img class="frame left" src="<?= $this->baseUrl('/images/web/pics/rob.jpg'); ?>" width="220" height="330" alt="Rob Grant" />
        <p>
            Rob Brown is a world leading authority on networking and business relationships.
            He is author of over 50 publications, including the bestseller &lsquo;How to Build Your
            Reputation&rsquo;. Rob is head of the <a href="http://www.globalnetworkingcouncil.com/" target="_blank" title="Go to the Global Network Council website. (opens in a new window)" alt="Global Networking Council">Global Networking Council</a>,
            featuring the world's top 200 thought leaders, authors and gurus on presence,
            impact, networking, referrals, trust, influence, likeability and relationship
            capital. All of his work is dedicated to helping people make more money from
            networking and be the stand out choice for what they do.
        </p>
    </div>

    <div class="grid_6 omega">
        <h4>Grant Leboff</h4>
        <img class="frame right" src="<?= $this->baseUrl('/images/web/pics/grant.jpg'); ?>" width="220" height="330" alt="Grant Leboff" />
        <p>
            Grant Leboff is one of the UK&rsquo;s leading Sales and Marketing experts. His current
            book, &lsquo;Sticky Marketing&rsquo;, immediately went straight to number 1 in the
            Amazon Sales and Marketing Chart and went to number 5 in the overall Business Chart.
            Leboff&rsquo;s main focus is to address the massive changes that are taking place in a
            world that is constantly being introduced to new technologies and an evolving World
            Wide Web. He is now CEO of <a href="http://stickymarketing.com" target="_blank" title="Go to the Sticky Marketing website. (opens in a new window)" alt="Sticky Marketing">Sticky Marketing Club&reg; Ltd.</a>,
            which engages with
            businesses on effective Sales and Marketing strategies.
        </p>
    </div>

    <div class="clear"></div>
    <hr>

    <p>
        This conference is brought to you by BBA Link-up – sponsors of networking clubs at Wyboston
        Lakes for the past 5 years.
    </p>
    <p>The agenda includes these presentations:</p>

    <ul class="check">
        <li>
            <b>The Ten Biggest Networking Mistakes</b> - The worst things you can do or say at a
            networking event.
        </li>
        <li>
            <b>Networking for Referrals</b> - Seven networking secrets to create streams of high
            quality referrals.
        </li>
        <li>
            <b>Why Everything in Marketing Has Changed</b> - Understanding how to make sense of
            what the move to the web, digital and social media means for your business.
        </li>
        <li>
            <b>The Latest Trends</b> - What is going on right now, which you must understand in
            order to ensure your communications and business development is the best it can be.
        </li>
    </ul>

    <p>
        Registration from 9.30am, event finishes at 4pm. A 3-course lunch at the Executive Centre
        is included.
    </p>

    <p><b>£79 including VAT.</b></p>

    <p>
        Please register your interest by completing the <a href="<?= $this->url(array(
            'action' => 'booking-form'
        ), 'nbmc'); ?>" class="button"><b>booking form</b></a>, or call BBA on
        <span class="theme_color"><b>0845 838 0284</b></span> with any queries.
    </p>
</div>




