
<? $this->placeholder('intro')->captureStart(); ?>
<h2 class="left">Log <span class="theme_color">In</span></h2>
<h2 class="phone">Call Us: <span class="theme_color">0845</span>-838-0284 </h2>
<? $this->placeholder('intro')->captureEnd(); ?>

<div id="main" class="grid_8 alpha">
    <div class="grid_8">
        <?=$this->loginForm; ?>
    </div>
</div>

<aside id="aside" class="omega clearfix">
    <div class="sidebar-widget">
        <h5>BBA <span class="theme_color">Office</span></h5>
        <p>3A Market Square,
        <br>
        Sandy, Bedfordshire SG19 1HT</p>
        <p><b>Tel:</b> 0845-838-0284
        <br>
        <b>Fax:</b> 0845-838-0286
        <br>
        <b>E-mail:</b> <a href="mailto:info@b-b-a.co.uk">info@b-b-a.co.uk</a>
    </div>
</aside>