<div id="nbmcForm"
     data-dojo-type="dijit.Dialog"
     data-dojo-id="nbmcForm"
     data-dojo-props="
        title:'Create New Invoice',
        execute: sf.Nbmc.processForm
    ">
    <div class="dijitDialogPaneContentArea">
        <div id="formWrap">
            <h3 style="text-align:center;">Fill out form to create Invoice</h3>
            <?= $this->addForm; ?>
        </div>
    </div>
</div>