<div id="nbmcForm"
     data-dojo-type="dijit.Dialog"
     data-dojo-id="nbmcForm"
     data-dojo-props="
        title:'Edit Invoice <?= $this->row->getInvoiceNumber(); ?>',
        execute: sf.Nbmc.processForm
    ">
    <div class="dijitDialogPaneContentArea">
        <div id="formWrap">
            <h3 style="text-align:center;">Fill out form to edit Invoice</h3>
            <?= $this->editForm; ?>
        </div>
    </div>
</div>