<?php $this->headScript()->captureStart() ?>
    var sfModule = 'Nbmc';
    require(["admin/Nbmc"]);
<?php $this->headScript()->captureEnd() ?>


<div data-dojo-type="dijit.layout.ContentPane"
        data-dojo-props="region: 'top'">
    <form data-dojo-type="dijit.form.Form" id="Search">
    	<input type="text" id="nbmc" name="nbmc"
    		   data-dojo-type="dijit.form.TextBox"
    		   data-dojo-params="label: 'Search Term:'" />
        <button data-dojo-type="dijit.form.Button"
                type="submit"
                id="">Search</button>
         <button data-dojo-type="dijit.form.Button"
                type="reset"
                id="">Reset</button>
    </form>
</div>

<div data-dojo-type="dijit.layout.ContentPane"
     data-dojo-props="region: 'center'"
     class="contentPanels">
    <div id="nbmcGrid"></div>
    <div data-dojo-type="dijit.Menu" data-dojo-id="headerMenu" id="headerMenu" style="display: none;">
        <div data-dojo-type="dojox.widget.PlaceholderMenuItem" label="GridColumns"></div>
    </div>
    <div data-dojo-type="dijit.Menu" id="rowMenu" style="display: none;">
        <div data-dojo-type="dijit.MenuItem" id="nbmcExport">Export All to CVS</div>
        <div data-dojo-type="dijit.MenuItem" id="nbmcAdd">New Invoice</div>
        <div data-dojo-type="dijit.MenuItem" id="nbmcView">View Record</div>
        <div data-dojo-type="dijit.MenuItem" id="nbmcEdit">Edit Record</div>
        <div data-dojo-type="dijit.MenuItem" id="nbmcDelete">Delete Record</div>
    </div>
</div>

<div data-dojo-type="dijit.layout.ContentPane"
     data-dojo-props="region: 'right', splitter: true"
     class="contentPanels contentPanelRight"
     id="gridRowDetails">
    <h4>Double click on a row to see details.</h4>
</div>
