<? $this->placeholder('intro')->captureStart(); ?>
<h2 class="left">
    404 <span class="theme_color">Page</span>
</h2>
<? $this->placeholder('intro')->captureEnd(); ?>

  <div class="error404">&nbsp;</div>

  <?php if (isset($this->exception)): ?>

  <h3>Exception information:</h3>
  <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
  </p>

  <h3>Stack trace:</h3>
  <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
  </pre>

  <?php endif ?>