<div id="userForm"
     data-dojo-type="dijit.Dialog"
     data-dojo-id="userForm"
     data-dojo-props="
         title:'Add User',
         execute: sf.User.processForm
     ">
    <div class="dijitDialogPaneContentArea">
        <div id="userWrap">
            <h3 style="text-align:center;">Fill out form to add user</h3>
            <?= $this->addForm; ?>
        </div>
    </div>
</div>